/** Languages supported by speech / TTS generation */
export type SpeechLanguage = {
  name: string;
  code: string;
};

export const SPEECH_SUPPORTED_LANGUAGES: SpeechLanguage[] = [
  { name: 'English', code: 'en' },
  { name: 'Chinese (Simplified/Traditional)', code: 'zh' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Korean', code: 'ko' },
  { name: 'Spanish', code: 'es' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'Arabic', code: 'ar' },
  { name: 'Russian', code: 'ru' },
  { name: 'French', code: 'fr' },
  { name: 'German', code: 'de' },
  { name: 'Italian', code: 'it' },
  { name: 'Dutch', code: 'nl' },
  { name: 'Swedish', code: 'sv' },
  { name: 'Norwegian', code: 'no' },
  { name: 'Norwegian Nynorsk', code: 'nn' },
  { name: 'Danish', code: 'da' },
  { name: 'Finnish', code: 'fi' },
  { name: 'Polish', code: 'pl' },
  { name: 'Czech', code: 'cs' },
  { name: 'Slovak', code: 'sk' },
  { name: 'Hungarian', code: 'hu' },
  { name: 'Romanian', code: 'ro' },
  { name: 'Bulgarian', code: 'bg' },
  { name: 'Croatian', code: 'hr' },
  { name: 'Serbian', code: 'sr' },
  { name: 'Bosnian', code: 'bs' },
  { name: 'Slovenian', code: 'sl' },
  { name: 'Estonian', code: 'et' },
  { name: 'Latvian', code: 'lv' },
  { name: 'Lithuanian', code: 'lt' },
  { name: 'Ukrainian', code: 'uk' },
  { name: 'Belarusian', code: 'be' },
  { name: 'Greek', code: 'el' },
  { name: 'Turkish', code: 'tr' },
  { name: 'Hebrew', code: 'he' },
  { name: 'Persian (Farsi)', code: 'fa' },
  { name: 'Pashto', code: 'ps' },
  { name: 'Kurdish', code: 'ku' },
  { name: 'Hindi', code: 'hi' },
  { name: 'Bengali', code: 'bn' },
  { name: 'Urdu', code: 'ur' },
  { name: 'Punjabi', code: 'pa' },
  { name: 'Gujarati', code: 'gu' },
  { name: 'Marathi', code: 'mr' },
  { name: 'Tamil', code: 'ta' },
  { name: 'Telugu', code: 'te' },
  { name: 'Kannada', code: 'kn' },
  { name: 'Malayalam', code: 'ml' },
  { name: 'Sanskrit', code: 'sa' },
  { name: 'Assamese', code: 'as' },
  { name: 'Nepali', code: 'ne' },
  { name: 'Sinhala', code: 'si' },
  { name: 'Sindhi', code: 'sd' },
  { name: 'Tibetan', code: 'bo' },
  { name: 'Khmer', code: 'km' },
  { name: 'Burmese', code: 'my' },
  { name: 'Thai', code: 'th' },
  { name: 'Vietnamese', code: 'vi' },
  { name: 'Indonesian', code: 'id' },
  { name: 'Malay', code: 'ms' },
  { name: 'Filipino / Tagalog', code: 'tl' },
  { name: 'Javanese', code: 'jw' },
  { name: 'Kazakh', code: 'kk' },
  { name: 'Mongolian', code: 'mn' },
  { name: 'Georgian', code: 'ka' },
  { name: 'Armenian', code: 'hy' },
  { name: 'Azerbaijani', code: 'az' },
  { name: 'Swahili', code: 'sw' },
  { name: 'Yoruba', code: 'yo' },
  { name: 'Shona', code: 'sn' },
  { name: 'Amharic', code: 'am' },
  { name: 'Afrikaans', code: 'af' },
  { name: 'Haitian Creole', code: 'ht' },
  { name: 'Welsh', code: 'cy' },
  { name: 'Basque', code: 'eu' },
  { name: 'Catalan', code: 'ca' },
  { name: 'Galician', code: 'gl' },
  { name: 'Breton', code: 'br' },
  { name: 'Latin', code: 'la' },
  { name: 'Māori', code: 'mi' },
  { name: 'Yiddish', code: 'yi' },
  { name: 'Icelandic', code: 'is' },
  { name: 'Faroese', code: 'fo' },
];
