import {
  Activity,
  AlertTriangle,
  Anchor,
  Archive,
  ArrowRight,
  Atom,
  Award,
  Banknote,
  BarChart,
  BarChart3,
  Battery,
  Bell,
  Bird,
  Book,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  Building,
  Building2,
  Bus,
  Calendar,
  Camera,
  Car,
  Castle,
  Cat,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  Church,
  Circle,
  Clapperboard,
  Clock,
  Code,
  Coffee,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Cross,
  Crown,
  Database,
  Dna,
  Dog,
  DollarSign,
  Drama,
  Dumbbell,
  Factory,
  FileText,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Gauge,
  Gavel,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  HeartHandshake,
  Infinity as InfinityIcon,
  Key,
  Landmark,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  LineChart,
  Lock,
  Luggage,
  Map,
  MapPin,
  MapPinned,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Moon,
  MoonStar,
  Mountain,
  Music,
  Network,
  Newspaper,
  Orbit,
  Paintbrush,
  Palette,
  Pen,
  Pencil,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Podcast,
  Puzzle,
  Quote,
  Radio,
  Receipt,
  Ribbon,
  Rocket,
  Rss,
  Satellite,
  Scale,
  Scroll,
  Search,
  Server,
  Shield,
  Ship,
  Shirt,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Sword,
  Target,
  Telescope,
  Tent,
  Terminal,
  Theater,
  Thermometer,
  Timer,
  Train,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  User,
  Users,
  UsersRound,
  Utensils,
  Vote,
  Wallet,
  Waves,
  Wifi,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Keys are lowercase with hyphens/underscores stripped (`arrow-right` → `arrowright`). */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  alerttriangle: AlertTriangle,
  alert: AlertTriangle,
  anchor: Anchor,
  archive: Archive,
  arrowright: ArrowRight,
  atom: Atom,
  award: Award,
  banknote: Banknote,
  barchart: BarChart,
  barchart3: BarChart3,
  battery: Battery,
  bell: Bell,
  bird: Bird,
  book: Book,
  brain: Brain,
  braincircuit: BrainCircuit,
  briefcase: Briefcase,
  bug: Bug,
  building: Building,
  building2: Building2,
  bus: Bus,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  castle: Castle,
  cat: Cat,
  chartcolumn: ChartColumn,
  chartline: ChartLine,
  chartpie: ChartPie,
  check: Check,
  church: Church,
  circle: Circle,
  clapperboard: Clapperboard,
  clock: Clock,
  code: Code,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  cpu: Cpu,
  creditcard: CreditCard,
  cross: Cross,
  crown: Crown,
  database: Database,
  dna: Dna,
  dog: Dog,
  dollarsign: DollarSign,
  drama: Drama,
  dumbbell: Dumbbell,
  factory: Factory,
  filetext: FileText,
  file: FileText,
  film: Film,
  fingerprint: Fingerprint,
  fingerprintpattern: Fingerprint,
  fish: Fish,
  flag: Flag,
  flame: Flame,
  flaskconical: FlaskConical,
  folder: Folder,
  gauge: Gauge,
  gavel: Gavel,
  globe: Globe,
  graduationcap: GraduationCap,
  handshake: Handshake,
  heart: Heart,
  hearthandshake: HeartHandshake,
  infinity: InfinityIcon,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  linechart: LineChart,
  lock: Lock,
  luggage: Luggage,
  map: Map,
  mappin: MapPin,
  mappinned: MapPinned,
  medal: Medal,
  megaphone: Megaphone,
  messagecircle: MessageCircle,
  message: MessageCircle,
  mic: Mic,
  microscope: Microscope,
  moon: Moon,
  moonstar: MoonStar,
  mountain: Mountain,
  music: Music,
  network: Network,
  newspaper: Newspaper,
  orbit: Orbit,
  paintbrush: Paintbrush,
  palette: Palette,
  pen: Pen,
  pencil: Pencil,
  piechart: PieChart,
  piggybank: PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  podcast: Podcast,
  puzzle: Puzzle,
  quote: Quote,
  radio: Radio,
  receipt: Receipt,
  ribbon: Ribbon,
  rocket: Rocket,
  rss: Rss,
  satellite: Satellite,
  scale: Scale,
  scroll: Scroll,
  search: Search,
  server: Server,
  shield: Shield,
  ship: Ship,
  shirt: Shirt,
  smartphone: Smartphone,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  sword: Sword,
  target: Target,
  telescope: Telescope,
  tent: Tent,
  terminal: Terminal,
  theater: Theater,
  thermometer: Thermometer,
  timer: Timer,
  train: Train,
  trendingdown: TrendingDown,
  trendingup: TrendingUp,
  trophy: Trophy,
  tv: Tv,
  umbrella: Umbrella,
  user: User,
  users: Users,
  usersround: UsersRound,
  utensils: Utensils,
  vote: Vote,
  wallet: Wallet,
  waves: Waves,
  wifi: Wifi,
  wind: Wind,
  x: X,
  zap: Zap,
};

export function resolveLucideIcon(name: string): LucideIcon {
  const key = name.trim().toLowerCase().replace(/[\s_-]+/g, '');
  return ICONS[key] ?? Circle;
}

/** Hand-drawn 24×24 strokes so the preview never depends on Lucide painting. */
const INLINE_PATHS: Record<string, string[]> = {
  arrowright: ['M5 12h14', 'm12 5 7 7-7 7'],
  arrowleft: ['M19 12H5', 'm12 19-7-7 7-7'],
  arrowup: ['M12 19V5', 'm5 12 7-7 7 7'],
  arrowdown: ['M12 5v14', 'm19 12-7 7-7-7'],
};

/** Lucide SVG for Remotion + timeline preview. Pixel size + stroke so scale() cannot hide it. */
export function LucideIconView({
  name,
  size = 64,
  color = 'white',
}: {
  name?: string;
  size?: number;
  color?: string;
}) {
  if (!name?.trim()) return null;
  const key = name.trim().toLowerCase().replace(/[\s_-]+/g, '');
  const paths = INLINE_PATHS[key];
  const svgStyle = {
    display: 'block',
    width: size,
    height: size,
    minWidth: size,
    minHeight: size,
    flexShrink: 0,
    overflow: 'visible' as const,
    color,
  };
  if (paths) {
    return (
      <svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke={color}
        strokeWidth={2.75}
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
        style={svgStyle}
      >
        {paths.map((d) => (
          <path key={d} d={d} />
        ))}
      </svg>
    );
  }
  const Cmp = resolveLucideIcon(name);
  return (
    <Cmp
      size={size}
      color={color}
      strokeWidth={2.5}
      fill="none"
      style={svgStyle}
    />
  );
}
